force_quit = ["ctrl-c"]
quit = ["q"]
help_toggle = ["?"]
cancel = ["esc"]
close = ["backspace"]

navigate_up = ["k", "up"]
navigate_down = ["j", "down"]
navigate_right = ["l", "right"]
navigate_left = ["h", "left"]
go_to_parent = ["alt-j", "alt-down"]
select_up = ["shift-k"]
select_down = ["shift-j"]

go_to_top = ["g"]
go_to_bottom = ["shift-g"]
scroll_down = ["ctrl-e"]
scroll_up = ["ctrl-y"]
page_up = ["ctrl-b", "pageup"]
page_down = ["ctrl-f", "pagedown", "space"]
half_page_up = ["ctrl-u"]
half_page_down = ["ctrl-d"]
select_top = ["shift-h"]
select_middle = ["shift-m"]
select_bottom = ["shift-l"]

go_to_next = ["n"]
go_to_previous = ["shift-n"]
confirm = ["enter"]
ref_list_toggle = ["tab"]
search = ["/"]
filter = ["f"]
ignore_case_toggle = ["ctrl-g"]
fuzzy_toggle = ["ctrl-x"]

user_command_view_toggle_1 = ["d"]

# copy part of information, ex: copy the short commit hash not all
short_copy = ["c"]
full_copy = ["shift-c"]

create_tag = ["t"]
delete_tag = ["ctrl-t"]

refresh = ["r"]
