force_quit = ["ctrl-c"]
quit = ["q"]
help_toggle = ["?"]
cancel = ["esc"]
close = ["backspace"]

navigate_up = ["k", "up"]
navigate_down = ["j", "down"]
navigate_right = ["l", "right"]
navigate_left = ["h", "left"]
go_to_parent = ["alt-j", "alt-down"]

go_to_top = ["g"]
go_to_bottom = ["shift-g"]
scroll_down = ["ctrl-e"]
scroll_up = ["ctrl-y"]
page_up = ["ctrl-b", "pageup"]
page_down = ["ctrl-f", "pagedown", "space"]
half_page_up = ["ctrl-u"]
half_page_down = ["ctrl-d"]
select_top = ["shift-h"]
select_middle = ["shift-m"]
select_bottom = ["shift-l"]

go_to_next = ["n"]
go_to_previous = ["shift-n"]
confirm = ["enter"]
ref_list_toggle = ["tab"]
search = ["/"]
ignore_case_toggle = ["ctrl-g"]

# copy part of information, ex: copy the short commit hash not all
short_copy = ["c"]
full_copy = ["shift-c"]
